#!/usr/bin/bash
TARGET_NAMESPACE=b2b
IMG_NAME=ibmscc-docker-image
# command to create ibm entitlement secret
oc create secret docker-registry ibm-entitlement-key --docker-username=cp --docker-password=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE1ODk0MjUwNDAsImp0aSI6IjIxYWYxMTJmYTVjNjQ4OGJhYzZmNzdkYWI4Yjc0ZTlmIn0.m7jxD8n7kZZAUP3Xennge9bBEMns1_7E_8XCj5fdNWA --docker-server=cp.icr.io --namespace=b2b

# Secret can also be created using individual yaml files.
#oc apply -f ibm-entitlement-key.yaml -n $TARGET_NAMESPACE
#create a git secret
oc apply -f bbksecret.yml -n $TARGET_NAMESPACE
#create imagestream
oc create imagestream ibmscc-poc -n $TARGET_NAMESPACE

#create build config
oc apply -f sccm-buildconfig.yaml
# Start the build
oc start-build ibm-sccm-poc


kind: Secret
apiVersion: v1
metadata:
  name: bbksecret
  namespace: b2b
data:
  password: T3emhOV21oaGY=
  username: bXVhNzc5bQ==
type: kubernetes.io/basic-auth

kind: Secret
apiVersion: v1
metadata:
  name: ibm-entitlement-key
  namespace: b2b
  data:
  .dockerconfigjson: >-
    eyJhbGciOiJIUzE_8XCj5fdNWA
type: kubernetes.io/dockerconfigjson


apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ibm-sccm-poc
  namespace: b2b
spec:
  source:
    type: Git
    git:
      uri: https://bbk.k.com/scm/mft/mft-demos.git
#      ref: "feature-mqcloudpak-v1.0"
    contextDir: "ibm-sccm/sccm6201/ibm-sccm/base-image"
    sourceSecret:
      name: bbksecret
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      pullSecret:
        name: ibm-entitlement-key
  output:
    to:
      kind: ImageStreamTag
      name: 'ibmscc-poc:mufg_2022-03-30_ibmscc_6210_iFix05'
